### ISSUE TITLE
[refactor]: Use destructuring instead!

### ISSUE THREAD

**Issue by hadihammurabi** [andi-faizal94/API-typeorm-express#1]
Related code: https://github.com/andi-faizal94/API-typeorm-express/blob/b5422161d47f07e5439403ed772d6c7c9f30fab4/src/routes/Blog.ts?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L8

Problem:
To much line to get data from body. Better use object destructuring.

Recommendation:
```js
const { title_blog: titleBlog, content_blog: contentBlog } = req.body;
```

**Comment by andi-faizal94** [comment]
Thanks a lot Mas Robi

**Comment by hadihammurabi** [comment]
> Thanks a lot Mas Robi

Asiap

**Comment by hadihammurabi** [comment]
wahhh belom dibener-benerin ni, Mas @andi-faizal94  🤣

**Comment by andi-faizal94** [comment]
weh aku kelupaan mas, wkwkwkw ini bagaimana closenya ya. wkwkwkw

**Comment by andi-faizal94** [comment]
Sudah aku closed mas wkwkkww.
